default_install_hook_types: [pre-commit, pre-push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: no-commit-to-branch
        args: [--branch, aprendiendo-github-actions]
        stages: [pre-commit, pre-push]